spring:
  application:
    name: cacheapp
  datasource:
    url: jdbc:postgresql://localhost:5432/cacheapp
    username: postgres
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type:
      redis
    redis:
      time-to-live: 60000 # 1 minute TTL

cache:
  expiration: 300  # Cache TTL in seconds



